print("Salom! Bu fay githubga yuklandi")
print("uchunchi qator qo'shildi")
print("to'rtinchi qator qo'shildi")
print("beshinchi qator qo'shildi")
print("12 dekabr birinchi qator saytda qo'shildi")
print("12 dekabr ikkinchi qator Pycharmda qo'shildi")